#!/bin/bash

job_regenerate_locales()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_regenerate_locales"

	#
	# cleanup and regenerate locales
	#

	# clean out unneeded comments and stuff
	cat ${mountpoint}/etc/locale.gen | grep "#" | grep -v "live system" > ${mountpoint}/etc/locale.gen.new
	rm -rf ${mountpoint}/etc/locale.gen
	mv ${mountpoint}/etc/locale.gen.new ${mountpoint}/etc/locale.gen

	# enable glibc locales from rc.conf
	for i in $(grep "^LOCALE" ${mountpoint}/etc/rc.conf | sed -e 's/.*="//g' -e's/\..*//g'); do
		sed -i -e "s/^#$i/$i/g" ${mountpoint}/etc/locale.gen
	done

	# always enable en_US
	sed -i 's/^#\(en_US.*\)/\1/' ${mountpoint}/etc/locale.gen

	# finally, regenerate the locales
	chroot ${mountpoint} /usr/sbin/locale-gen

	msg_job_done
}
