#!/bin/bash

job_download_l10n()
{
	msg_job_start "job_download_l10n"

	mount -v -t proc none ${mountpoint}/proc 
	mount -v -t sysfs none ${mountpoint}/sys 
	mount -v -o bind /dev ${mountpoint}/dev 
	
	if [ "${kdelang}" != "" ] ; then

		if [ "${ping_check}" != "" ] ; then
			pkg_installed=`pacman -Q --noconfirm | grep ${KDE_L10N_PREFIX}-${kdelang}`
			pkg_check=`pacman -Ss ${KDE_L10N_PREFIX}-${kdelang} --noconfirm | grep ${KDE_L10N_PREFIX}-${kdelang}`
			if [ "${pkg_check}" = "" ] || [ "${pkg_installed}" != "" ]; then
				msg "no ${KDE_L10N_PREFIX}-${kdelang} available or already installed. skipping"
			else
				msg "installing ${KDE_L10N_PREFIX}-${kdelang}"
				chroot ${mountpoint} /usr/bin/pacman -Syf ${KDE_L10N_PREFIX}-${kdelang} --noconfirm
			fi
		else
			msg "no internet connection available. skipping"
		fi

	else
		
		msg "l10n download disabled"

	fi
	
	msg "umounting /proc, /sys and /dev"
	umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev 

	msg_job_done
}
