#!/bin/bash

job_cleanup_drivers()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_cleanup_drivers"

	mount -v -t proc none ${mountpoint}/proc 
	mount -v -t sysfs none ${mountpoint}/sys 
	mount -v -o bind /dev ${mountpoint}/dev 


	###########################################################################
	# CLEANUP XORG DRIVERS
	###########################################################################
	msg "cleaning up video drivers"

	USED_DRIVER=`cat /etc/X11/xorg.conf | sed -n '/Section.*."Device"/,/EndSection/p' | grep -v "#" | grep Driver | cut -d '"' -f 2`
	ALL_DRIVERS=`pacman -r ${mountpoint} -Q | grep xf86-video | cut -d "-" -f 3 | cut -d " " -f 1 | grep -v vesa`
	ALL_INSTALLEDDRI=`pacman -r ${mountpoint} -Q | grep dri | cut -d " " -f 1 | grep -v dri2proto`

	msg "configured driver: ${USED_DRIVER}"
	msg "installed drivers: ${ALL_DRIVERS}"

	#workarounds for drivers where xf86-video-$driver != ${USED_DRIVER}
	if [ "${USED_DRIVER}" = "radeon" ] ; then
		unset ${USED_DRIVER}
		USED_DRIVER="ati"
	fi

	if [ "${USED_DRIVER}" = "mach64" ] ; then
		unset ${USED_DRIVER}
		USED_DRIVER="ati"
	fi

	if [ "${USED_DRIVER}" = "r128" ] ; then
		unset ${USED_DRIVER}
		USED_DRIVER="ati"
	fi

	# proprietary driver handling
	if [ -e "/tmp/nvidia" ] ; then
					for driver in ${ALL_DRIVERS}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn xf86-video-${driver} --noconfirm
					done

					for dri in ${ALL_INSTALLEDDRI}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn ${dri} --noconfirm
					done

	elif [ -e "/tmp/nvidia-71xx" ] ; then
					for driver in ${ALL_DRIVERS}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn xf86-video-${driver} --noconfirm
					done

					for dri in ${ALL_INSTALLEDDRI}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn ${dri} --noconfirm
					done

	elif [ -e "/tmp/nvidia-96xx" ] ; then
					for driver in ${ALL_DRIVERS}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn xf86-video-${driver} --noconfirm
					done

					for dri in ${ALL_INSTALLEDDRI}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn ${dri} --noconfirm
					done

	elif [ -e "/tmp/nvidia-173xx" ] ; then
					for driver in ${ALL_DRIVERS}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn xf86-video-${driver} --noconfirm
					done

					for dri in ${ALL_INSTALLEDDRI}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn ${dri} --noconfirm
					done

	elif [ -e "/tmp/catalyst" ] ; then
					for driver in ${ALL_DRIVERS}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn xf86-video-${driver} --noconfirm
					done

					for dri in ${ALL_INSTALLEDDRI}
					do
							chroot ${mountpoint} /usr/bin/pacman -Rn ${dri} --noconfirm
					done

	else
					for driver in ${ALL_DRIVERS}
					do
						if [ "${driver}" != "${USED_DRIVER}" ] ; then
							chroot ${mountpoint} /usr/bin/pacman -Rn xf86-video-${driver} --noconfirm
						fi
					done
	fi
	msg "video driver removal complete"



	###########################################################################
	# CLEANUP INPUT DRIVERS
	###########################################################################
	msg "cleaning up input drivers"

	USED_IDRIVER=`cat /etc/X11/xorg.conf | sed -n '/Section.*."InputDevice"/,/EndSection/p' | grep -v "#" | grep Driver | cut -d '"' -f 2`
	ALL_IDRIVERS=`pacman -r ${mountpoint} -Q | grep xf86-input | cut -d "-" -f 3 | cut -d " " -f 1 | grep -v keyboard | grep -v evdev | grep -vw mouse`

	for i in $USED_IDRIVER
	do
		if [ "${i}" = "acecad" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "aiptek" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "calcomp" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "citron" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "digitaledge" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "dmc" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "dynapro" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "elo2300" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "elographics" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "fpit" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "hyperpen" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "jamstudio" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "joystick" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "magellan" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "magictouch" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "microtouch" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "mutouch" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "palmax" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "penmount" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "spaceorb" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "summa" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "evdev" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "tek4957" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "ur98" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "vmmouse" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "void" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`

		elif [ "${i}" = "wacom" ] ; then
			ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"${i}"/""/g`
		fi
	done

	#check for synaptics driver
	if cat /var/log/Xorg.0.log | grep "synaptics" > 0 ; then
		ALL_IDRIVERS=`echo $ALL_IDRIVERS | sed s/"synaptics"/""/g`
	fi

	for driver in ${ALL_IDRIVERS}
	do
		chroot ${mountpoint} /usr/bin/pacman -Rn xf86-input-${driver} --noconfirm
	done
	
	msg "umounting /proc, /sys and /dev"
	umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev 

	msg "input driver removal complete"

	msg_job_done
}
